version: 2
jobs:
  build-scheduled:
    docker:
      - image: buildpack-deps:stretch-scm
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Trigger Docker hub build
          command: | 
            curl -H "Content-Type: application/json" --data '{"build": true}' -XPOST https://hub.docker.com/api/build/v1/source/${DOCKER_HUB_PROJECT_ID}/trigger/${TOKEN}/call/
  build:
    docker:
      - image: buildpack-deps:stretch-scm
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -s -L -o /tmp/docker-latest.tgz https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
            tar -xz -C /tmp -f /tmp/docker-latest.tgz
            mv /tmp/docker/* /usr/bin
      - run: cd java8 && docker build .
      - run: cd java9 && docker build .
      - run: cd java10 && docker build .
      - run: cd java11 && docker build .
      - run: cd java8-browser-library && docker build .
      - run: cd java8-browser-awscli-library && docker build .
workflows:
  version: 2
  all:
    jobs:
      - build 
  scheduled:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-scheduled
